#!/usr/bin/env bash

# XDG_SESSION_TYPE=x11
# export XDG_SESSION_TYPE

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
# bspc config pointer_action1 move

bspc rule -a steam state=floating desktop=7
bspc rule -a Screenkey manage=off

systemctl --user import-environment DISPLAY
pgrep --full autostart.bash || ~/bin/autostart.bash x
