#!/usr/bin/env bash

# XDG_SESSION_TYPE=x11
# export XDG_SESSION_TYPE

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
# bspc config pointer_action1 move

bspc rule -a steam state=floating desktop=7
bspc rule -a Screenkey manage=off

systemctl --user import-environment DISPLAY

# Hotkey daemon
pgrep --exact sxhkd || sxhkd &>/dev/null &

pgrep --full eww_fullscreen_fix.bash || ~/.config/bspwm/eww_fullscreen_fix.bash &>/dev/null &
pgrep --full update_eww_status.bash || ~/.config/bspwm/update_eww_status.bash &>/dev/null &

# Display Power Management Signaling
xset s 170 170
xset dpms 180 180 180

pgrep --exact polkit-mate-aut || /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &>/dev/null &
pgrep --exact xss-lock || xss-lock --transfer-sleep-lock -- i3lock -c 1a1b26 --nofork &>/dev/null &
pgrep --exact dunst || dunst &>/dev/null &
pgrep --exact picom || picom &>/dev/null &
pgrep --exact flameshot || flameshot &>/dev/null &
ln -sf ~/.local/bin/eww-x ~/.local/bin/eww && eww daemon &>/dev/null && eww open bar &>/dev/null
[[ -f ~/wallpaper.jpg ]] && feh --no-fehbg --bg-fill ~/wallpaper.jpg
