set nocompatible
set autoread
set clipboard=unnamedplus
set fileformat=unix
set hlsearch
set ruler
set laststatus=2
set encoding=utf-8
set showmatch
set noswapfile
set cursorline
set splitbelow splitright
set history=100

set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smartindent
set number relativenumber

set ignorecase
set smartcase

set wrap
set linebreak

" gvim
set guioptions-=m  "menu bar
set guioptions-=T  "toolbar
set guioptions-=r  "scrollbar

colorscheme habamax

filetype plugin on
syntax enable

nnoremap <silent> <esc> :noh<cr><esc>

" replace currently selected text with default register without yanking it
"vmap p "_dP

function! <SID>StripTrailingWhitespaces()
  if !&binary && &filetype != 'diff'
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
  endif
endfun

autocmd BufWritePre,FileWritePre,FileAppendPre,FilterWritePre *
  \ :call <SID>StripTrailingWhitespaces()

