[workspace]
members = ["wp"]
resolver = "2"

[package]
name = "smolscripts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nvidia_fan_control"

[profile.release]
codegen-units = 1
lto = true
# debug = true

# Optimizes dependencies
[profile.dev.package."*"]
opt-level = 3
debug = false
