#!/usr/bin/env zsh

if [[ $1 == "GUI" ]]; then
    shift
    FONT="JetBrains Mono"
    if [[ $# -eq 0 ]]; then
        alacritty --option="font.normal.family=$FONT" --option="font.bold.family=$FONT" --option="font.italic.family=$FONT" --option="font.bold_italic.family=$FONT" --command=/usr/bin/nvim
    else
        alacritty --option="font.normal.family=$FONT" --option="font.bold.family=$FONT" --option="font.italic.family=$FONT" --option="font.bold_italic.family=$FONT" --command=/usr/bin/nvim --command="$*"
    fi
else
    /usr/bin/nvim "$@"
fi
