[manager]
sort_by = "natural"
sort_dir_first = true
linemode = "size"

[preview]
max_width = 600
max_height = 600
cache_dir = "~/.cache/yazi/"

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
open = [{ run = 'handlr open "$@"' }]
img = [{ run = 'imv-dir "$@"', orphan = true }]
img_edit = [{ run = 'krita "$@"', orphan = true }]
play = [{ run = 'mpv --no-pause --player-operation-mode=pseudo-gui "$@"', orphan = true }]
reveal = [{ run = 'handlr open "$(dirname "$0")"', desc = "Reveal" }]

[open]
rules = [
    { mime = "image/*", use = [ "img", "img_edit", "open", "reveal" ] },
    { mime = "{audio,video}/*", use = [ "play", "open", "reveal" ] },
    { name = "*.ivf", use = [ "play", "open", "reveal" ] },
    { name = "*.cue", use = [ "play", "edit", "open", "reveal" ] },

    { mime = "text/*", use = [ "edit", "open", "reveal" ] },

    { mime = "application/*zip", use = [ "open", "reveal" ] },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "open", "reveal" ] },

    { name = "*", use = [ "open", "edit", "reveal" ] },
]

[tasks]
suppress_preload = true

[plugin]
prepend_preloaders = [
    { mime = "{audio,video}/*", run = "noop" },
]
